#!/usr/bin/env ruby
# frozen_string_literal: true

require "rockette"

Signal.trap("INT") do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Rockette::CLI.start
rescue Rockette::CLI::Error => e
  puts "ERROR: #{e.message}"
  exit 1
end
