#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'rockette/cli'

CONF = JSON.parse(File.read('config.json'))
ENV["THOR_SILENCE_DEPRECATION"] = "true"

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Rockette::CLI.start
rescue Rockette::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end